name: quick-recipe
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython
  - pytorch
  - torchvision
  - cudatoolkit
  - pip:
    - opencv-python
    - numpy
    - pandas
    - yt-dlp
    - omegaconf
    - tqdm
    - ipywidgets