name: pytorch-image-captioning
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - numpy=1.21.4
  - pillow=8.4.0
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.10.0
  - tensorboardx=2.4
  - torchvision=0.11.1
  - pip:
    - matplotlib==3.5.0
